<?php

require_once 'init.php';

/**
 * Test class for Scaffold_Loader.
 * Generated by PHPUnit on 2010-06-13 at 15:09:41.
 */
class Scaffold_LoaderTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Scaffold_Loader
     */
    protected $object;
    protected $load_paths = array();

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Scaffold_Loader($this->load_paths);
    }

    /**
     * @todo Implement testFile().
     */
    public function testFile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testString().
     */
    public function testString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
    
    public function testFind()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
    
    public function testValid_file()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}

