<?php
require_once 'PHPUnit/Framework.php';
require_once '/Users/anthonyshort/Dropbox/Projects/Scaffold/Latest/lib/Scaffold/Engine/Constants.php';

/**
 * Test class for Scaffold_Engine_Constants.
 * Generated by PHPUnit on 2010-04-02 at 16:51:30.
 */
class Scaffold_Engine_ConstantsTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Scaffold_Engine_Constants
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Scaffold_Engine_Constants;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testExtract().
     */
    public function testExtract()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSet().
     */
    public function testSet()
    {
    	$this->object->set('Foo','Bar');
    }

    /**
     * @todo Implement testRemove().
     */
    public function testRemove()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGet().
     */
    public function testGet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testReplace().
     */
    public function testReplace()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testParse_xml().
     */
    public function testParse_xml()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
